/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"

void * initialize_random_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

double * get_next_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static double  result;
	result = (rand() / (double)RAND_MAX * 19) + 1;
	
	return &result;
}
