/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RAND_H_RPCGEN
#define _RAND_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct params {
	int xleft;
	int xright;
};
typedef struct params params;

#define RAND_PROG 0x30000000
#define RAND_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_NEXT_RANDOM 1
extern  int * get_next_random_1(params *, CLIENT *);
extern  int * get_next_random_1_svc(params *, struct svc_req *);
extern int rand_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_NEXT_RANDOM 1
extern  int * get_next_random_1();
extern  int * get_next_random_1_svc();
extern int rand_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_params (XDR *, params*);

#else /* K&R C */
extern bool_t xdr_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RAND_H_RPCGEN */
